// Build-time content export: regenerate src/data/content.generated.ts from the
// live DB (via the API's GET /api/content), so the Postgres content managed in
// Master Control is what the bundled player app ships. See master-control-plan.md §5.
//
// Run automatically by `npm run build` (before tsc/vite). RESILIENT BY DESIGN:
// if the API is unreachable (e.g. a CI build with no server, or the very first
// deploy before the new API is up), it logs and KEEPS the committed
// content.generated.ts, so the build never breaks and stays reproducible from
// the repo alone.
//
// Resolve the API base from FFC_CONTENT_URL, else PORT (env or server/.env),
// else 8060 — matching bin/ffc's port resolution.
import { readFile, writeFile } from "node:fs/promises";
import { fileURLToPath } from "node:url";
import { dirname, join } from "node:path";

const __dirname = dirname(fileURLToPath(import.meta.url));
const ROOT = join(__dirname, "..");
const OUT = join(ROOT, "src", "data", "content.generated.ts");

async function resolvePort() {
  if (process.env.PORT) return process.env.PORT;
  for (const p of [join(ROOT, "server", ".env"), join(ROOT, ".env")]) {
    try {
      const txt = await readFile(p, "utf8");
      const m = txt.match(/^\s*(?:export\s+)?PORT=(\d+)/m);
      if (m) return m[1];
    } catch {
      /* no .env here — fine */
    }
  }
  return "8060";
}

const lit = (v) => JSON.stringify(v ?? null);

function renderLocation(l) {
  return `  {
    id: ${lit(l.id)},
    name: ${lit(l.name)},
    slug: ${lit(l.slug)},
    lat: ${lit(l.lat)},
    lng: ${lit(l.lng)},
    geofenceKm: ${lit(l.geofenceKm)},
    tz: ${lit(l.tz)},
    sortOrder: ${lit(l.sortOrder ?? 0)},
    menuUrl: ${lit(l.menuUrl)},
    orderingUrl: ${lit(l.orderingUrl)},
    hours: ${lit(l.hours)},
    venueHunt: ${lit(l.venueHunt ?? false)},
    pos: ${lit(l.pos)},
    orgId: ${lit(l.orgId)},
  },`;
}

// The org rides in the payload with SPARSE branding (only the keys the org
// stored — the client merges its own defaults, src/lib/branding.ts); only the
// fields the client types (id/slug/name/branding) are baked, and a payload
// without a resolvable tenant bakes null.
function renderOrg(o) {
  if (!o || typeof o.id !== "string") return "null";
  return `{
  id: ${lit(o.id)},
  slug: ${lit(o.slug)},
  name: ${lit(o.name)},
  branding: ${lit(o.branding && typeof o.branding === "object" ? o.branding : {})},
}`;
}

function renderCourse(c) {
  return `  {
    id: ${lit(c.id)},
    locationId: ${lit(c.locationId)},
    name: ${lit(c.name)},
    theme: ${lit(c.theme)},
    holeCount: ${lit(c.holeCount ?? 18)},
    pars: ${JSON.stringify(c.pars)},
    sortOrder: ${lit(c.sortOrder ?? 0)},
    hasHunt: ${lit(c.hasHunt ?? false)},
  },`;
}

export function render(locations, courses, org = null) {
  return `// AUTO-GENERATED by scripts/export-content.mjs — DO NOT EDIT BY HAND.
// The Postgres DB (managed in Master Control) is the source of truth; this file
// is regenerated at build time from GET /api/content and committed so builds are
// reproducible without a live DB. Frontend-only styling (accents, themed rules,
// map art) is merged on top in src/data/courses.ts. See master-control-plan.md §5.

// Weekly business hours (per venue, set in Master Control), evaluated in the
// location's own \`tz\`. A missing day key = closed; a day may instead be the
// string "closed"; \`close\` may be "24:00" (midnight) or earlier than \`open\`
// for an overnight close. See src/lib/venueHours.ts (mirrors
// server/lib/venueHours.js) for the canonical shape doc + open/closed logic.
export type VenueHoursDay = { open: string; close: string } | 'closed';
export type VenueHours = Partial<
  Record<'mon' | 'tue' | 'wed' | 'thu' | 'fri' | 'sat' | 'sun', VenueHoursDay>
>;

export type GeneratedLocation = {
  id: string;
  name: string;
  slug: string;
  lat: number | null;
  lng: number | null;
  geofenceKm: number | null;
  tz: string | null;
  sortOrder: number;
  menuUrl: string | null;
  orderingUrl: string | null;
  hours: VenueHours | null;
  // Course-free scavenger hunt availability, derived server-side (venueMode on
  // + at least one active venue item). Optional: an older snapshot or a cached
  // payload from a server that predates it simply won't carry the key.
  venueHunt?: boolean;
  // POS integration add-on (per-venue, set in Master Control). Structurally
  // matches PosConfig in src/lib/pos/types.ts (capabilities decoupled — each
  // names its own vendor); kept inline so this generated file stays
  // import-free.
  pos: {
    ordering: { vendor: string; apiBase: string | null } | null;
    loyalty: {
      vendor: string;
      apiBase: string | null;
      gameRewards: boolean;
      // Venue ticket-economy caps (enforced server-side by the award proxy;
      // carried here only so the config round-trips). Present only when the
      // venue overrides a default.
      gameRewardCaps?: { dailyPerCard: number | null; perGame: Record<string, number> };
    } | null;
  } | null;
  orgId: string | null;
};

export type GeneratedCourse = {
  id: string;
  locationId: string | null;
  name: string;
  theme: string;
  holeCount: number;
  pars: number[];
  sortOrder: number;
  // Whether this course has a hunt anyone can COMPLETE (active, non-countable
  // items). Optional: the baked snapshot predates it, and a cached payload from
  // an older server won't carry it. Absent reads as "assume it has one" — the
  // opposite of \`venueHunt\` above, and deliberately: that flag ADDS a surface,
  // this one GATES achievements off, and a stale cache must not silently hide
  // badges the deployment can actually grant (src/lib/achievements/detect.ts).
  hasHunt?: boolean;
};

// The tenant org the payload was filtered by (MULTI-VENUE.md §3), or null when
// the server resolved no tenant. \`branding\` is a partial overlay; the typed
// shape + defaults live in src/lib/branding.ts (kept loose here so this
// generated file stays import-free).
export type GeneratedOrg = {
  id: string;
  slug: string;
  name: string;
  branding: Record<string, string>;
};

export const GENERATED_ORG: GeneratedOrg | null = ${renderOrg(org)};

export const GENERATED_LOCATIONS: GeneratedLocation[] = [
${locations.map(renderLocation).join("\n")}
];

export const GENERATED_COURSES: GeneratedCourse[] = [
${courses.map(renderCourse).join("\n")}
];
`;
}

async function main() {
  const base = process.env.FFC_CONTENT_URL || `http://127.0.0.1:${await resolvePort()}`;
  const url = `${base.replace(/\/+$/, "")}/api/content`;
  try {
    const res = await fetch(url, { signal: AbortSignal.timeout(5000) });
    if (!res.ok) throw new Error(`HTTP ${res.status}`);
    const data = await res.json();
    if (!Array.isArray(data.locations) || !Array.isArray(data.courses)) {
      throw new Error("unexpected payload shape");
    }
    if (data.locations.length === 0) {
      // An empty catalog almost certainly means a fresh/empty DB, not a real
      // "no venues" state. Don't overwrite good committed content with nothing.
      console.warn(`[export-content] ${url} returned 0 locations — keeping committed content.generated.ts`);
      return;
    }
    await writeFile(OUT, render(data.locations, data.courses, data.org ?? null), "utf8");
    console.log(
      `[export-content] wrote ${data.locations.length} locations, ${data.courses.length} courses` +
        ` (org: ${data.org?.slug ?? "none"}) from ${url}`,
    );
  } catch (err) {
    console.warn(
      `[export-content] could not reach ${url} (${err.message}) — ` +
        `keeping committed content.generated.ts. Build continues.`
    );
  }
}

// Only run when invoked directly (so `render` can be imported for seeding/tests).
if (import.meta.url === `file://${process.argv[1]}`) {
  main();
}
