// Build-time content export: regenerate src/data/content.generated.ts from the
// live DB (via the API's GET /api/content), so the Postgres content managed in
// Master Control is what the bundled player app ships. See master-control-plan.md §5.
//
// Run automatically by `npm run build` (before tsc/vite). RESILIENT BY DESIGN:
// if the API is unreachable (e.g. a CI build with no server, or the very first
// deploy before the new API is up), it logs and KEEPS the committed
// content.generated.ts, so the build never breaks and stays reproducible from
// the repo alone.
//
// Resolve the API base from FFC_CONTENT_URL, else PORT (env or server/.env),
// else 8060 — matching bin/ffc's port resolution.
import { readFile, writeFile } from "node:fs/promises";
import { fileURLToPath } from "node:url";
import { dirname, join } from "node:path";

const __dirname = dirname(fileURLToPath(import.meta.url));
const ROOT = join(__dirname, "..");
const OUT = join(ROOT, "src", "data", "content.generated.ts");

async function resolvePort() {
  if (process.env.PORT) return process.env.PORT;
  for (const p of [join(ROOT, "server", ".env"), join(ROOT, ".env")]) {
    try {
      const txt = await readFile(p, "utf8");
      const m = txt.match(/^\s*(?:export\s+)?PORT=(\d+)/m);
      if (m) return m[1];
    } catch {
      /* no .env here — fine */
    }
  }
  return "8060";
}

const lit = (v) => JSON.stringify(v ?? null);

function renderLocation(l) {
  return `  {
    id: ${lit(l.id)},
    name: ${lit(l.name)},
    slug: ${lit(l.slug)},
    lat: ${lit(l.lat)},
    lng: ${lit(l.lng)},
    geofenceKm: ${lit(l.geofenceKm)},
    tz: ${lit(l.tz)},
    sortOrder: ${lit(l.sortOrder ?? 0)},
    orgId: ${lit(l.orgId)},
  },`;
}

function renderCourse(c) {
  return `  {
    id: ${lit(c.id)},
    locationId: ${lit(c.locationId)},
    name: ${lit(c.name)},
    theme: ${lit(c.theme)},
    holeCount: ${lit(c.holeCount ?? 18)},
    pars: ${JSON.stringify(c.pars)},
    sortOrder: ${lit(c.sortOrder ?? 0)},
  },`;
}

export function render(locations, courses) {
  return `// AUTO-GENERATED by scripts/export-content.mjs — DO NOT EDIT BY HAND.
// The Postgres DB (managed in Master Control) is the source of truth; this file
// is regenerated at build time from GET /api/content and committed so builds are
// reproducible without a live DB. Frontend-only styling (accents, themed rules,
// map art) is merged on top in src/data/courses.ts. See master-control-plan.md §5.

export type GeneratedLocation = {
  id: string;
  name: string;
  slug: string;
  lat: number | null;
  lng: number | null;
  geofenceKm: number | null;
  tz: string | null;
  sortOrder: number;
  orgId: string | null;
};

export type GeneratedCourse = {
  id: string;
  locationId: string | null;
  name: string;
  theme: string;
  holeCount: number;
  pars: number[];
  sortOrder: number;
};

export const GENERATED_LOCATIONS: GeneratedLocation[] = [
${locations.map(renderLocation).join("\n")}
];

export const GENERATED_COURSES: GeneratedCourse[] = [
${courses.map(renderCourse).join("\n")}
];
`;
}

async function main() {
  const base = process.env.FFC_CONTENT_URL || `http://127.0.0.1:${await resolvePort()}`;
  const url = `${base.replace(/\/+$/, "")}/api/content`;
  try {
    const res = await fetch(url, { signal: AbortSignal.timeout(5000) });
    if (!res.ok) throw new Error(`HTTP ${res.status}`);
    const data = await res.json();
    if (!Array.isArray(data.locations) || !Array.isArray(data.courses)) {
      throw new Error("unexpected payload shape");
    }
    if (data.locations.length === 0) {
      // An empty catalog almost certainly means a fresh/empty DB, not a real
      // "no venues" state. Don't overwrite good committed content with nothing.
      console.warn(`[export-content] ${url} returned 0 locations — keeping committed content.generated.ts`);
      return;
    }
    await writeFile(OUT, render(data.locations, data.courses), "utf8");
    console.log(`[export-content] wrote ${data.locations.length} locations, ${data.courses.length} courses from ${url}`);
  } catch (err) {
    console.warn(
      `[export-content] could not reach ${url} (${err.message}) — ` +
        `keeping committed content.generated.ts. Build continues.`
    );
  }
}

// Only run when invoked directly (so `render` can be imported for seeding/tests).
if (import.meta.url === `file://${process.argv[1]}`) {
  main();
}
