// GENERATED by scripts/vendor-icons.mjs — do not edit by hand.
// Re-run the script to change the mapping or pick up upstream fixes.
//
// Artwork from two sources, both copied in rather than imported, so only the
// icons the app actually uses ship and both packages stay devDependencies:
//
//   68 from Lucide (https://lucide.dev), ISC licence. Copyright (c) for
//   portions Lucide are held by Lucide Contributors 2022, and copyright for
//   portions of Feather are held by Cole Bemis 2013-2022.
//
//   7 from Phosphor Icons (https://phosphoricons.com), MIT licence,
//   copyright (c) 2023 Phosphor Icons. Bold weight, for arcade subjects Lucide
//   has no icon for. These are FILLED on a 256 grid — see FILLED_ART below.
//
// The stroke spec lives on <Icon>, not here, so these are restyled per skin by
// the same `.ffc-icon` rules as the hand-drawn arcade icons in registry.tsx.

import type { ReactNode } from 'react';
import type { IconName } from './manifest';

export const VENDORED_ART = {
  'nav.home': (
    <>
      {/* lucide/house */}
      <path d="M15 21v-8a1 1 0 0 0-1-1h-4a1 1 0 0 0-1 1v8" />
      <path d="M3 10a2 2 0 0 1 .709-1.528l7-6a2 2 0 0 1 2.582 0l7 6A2 2 0 0 1 21 10v9a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2z" />
    </>
  ),
  'nav.golf': (
    <>
      {/* lucide/flag-triangle-right */}
      {/* a pennant on a pole — the pin. state.finish takes the chequered flag. */}
      <path d="M6 22V2.8a.8.8 0 0 1 1.17-.71l11.38 5.69a.8.8 0 0 1 0 1.44L6 15.5" />
    </>
  ),
  'nav.arcade': (
    <>
      {/* lucide/gamepad-2 */}
      <line x1="6" x2="10" y1="11" y2="11" />
      <line x1="8" x2="8" y1="9" y2="13" />
      <line x1="15" x2="15.01" y1="12" y2="12" />
      <line x1="18" x2="18.01" y1="10" y2="10" />
      <path d="M17.32 5H6.68a4 4 0 0 0-3.978 3.59c-.006.052-.01.101-.017.152C2.604 9.416 2 14.456 2 16a3 3 0 0 0 3 3c1 0 1.5-.5 2-1l1.414-1.414A2 2 0 0 1 9.828 16h4.344a2 2 0 0 1 1.414.586L17 18c.5.5 1 1 2 1a3 3 0 0 0 3-3c0-1.545-.604-6.584-.685-7.258-.007-.05-.011-.1-.017-.151A4 4 0 0 0 17.32 5z" />
    </>
  ),
  'nav.food': (
    <>
      {/* lucide/utensils */}
      <path d="M3 2v7c0 1.1.9 2 2 2h4a2 2 0 0 0 2-2V2" />
      <path d="M7 2v20" />
      <path d="M21 15V2a5 5 0 0 0-5 5v6c0 1.1.9 2 2 2h3Zm0 0v7" />
    </>
  ),
  'nav.photos': (
    <>
      {/* lucide/camera */}
      {/* the device; action.take-photo takes the aperture, since 📸 served both. */}
      <path d="M13.997 4a2 2 0 0 1 1.76 1.05l.486.9A2 2 0 0 0 18.003 7H20a2 2 0 0 1 2 2v9a2 2 0 0 1-2 2H4a2 2 0 0 1-2-2V9a2 2 0 0 1 2-2h1.997a2 2 0 0 0 1.759-1.048l.489-.904A2 2 0 0 1 10.004 4z" />
      <circle cx="12" cy="13" r="3" />
    </>
  ),
  'nav.hunt': (
    <>
      {/* lucide/search */}
      <path d="m21 21-4.34-4.34" />
      <circle cx="11" cy="11" r="8" />
    </>
  ),
  'nav.me': (
    <>
      {/* lucide/user */}
      {/* the bare bust for the section; state.account takes the enclosed one. */}
      <path d="M19 21v-2a4 4 0 0 0-4-4H9a4 4 0 0 0-4 4v2" />
      <circle cx="12" cy="7" r="4" />
    </>
  ),
  'nav.locations': (
    <>
      {/* lucide/map-pin */}
      {/* the plain pin switches venue; state.located takes the checked pin. */}
      <path d="M20 10c0 4.993-5.539 10.193-7.399 11.799a1 1 0 0 1-1.202 0C9.539 20.193 4 14.993 4 10a8 8 0 0 1 16 0" />
      <circle cx="12" cy="10" r="3" />
    </>
  ),
  'nav.install': (
    <>
      {/* lucide/download */}
      <path d="M12 15V3" />
      <path d="M21 15v4a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2v-4" />
      <path d="m7 10 5 5 5-5" />
    </>
  ),
  'nav.rewards': (
    <>
      {/* lucide/ticket */}
      <path d="M2 9a3 3 0 0 1 0 6v2a2 2 0 0 0 2 2h16a2 2 0 0 0 2-2v-2a3 3 0 0 1 0-6V7a2 2 0 0 0-2-2H4a2 2 0 0 0-2 2Z" />
      <path d="M13 5v2" />
      <path d="M13 17v2" />
      <path d="M13 11v2" />
    </>
  ),
  'game.axe-throwing': (
    <>
      {/* lucide/axe */}
      <path d="m14 12-8.381 8.38a1 1 0 0 1-3.001-3L11 9" />
      <path d="M15 15.5a.5.5 0 0 0 .5.5A6.5 6.5 0 0 0 22 9.5a.5.5 0 0 0-.5-.5h-1.672a2 2 0 0 1-1.414-.586l-5.062-5.062a1.205 1.205 0 0 0-1.704 0L9.352 5.648a1.205 1.205 0 0 0 0 1.704l5.062 5.062A2 2 0 0 1 15 13.828z" />
    </>
  ),
  'game.darts': (
    <>
      {/* lucide/target */}
      {/* concentric rings. award.hole-in-one shared 🎯 and stays a badge. */}
      <circle cx="12" cy="12" r="10" />
      <circle cx="12" cy="12" r="6" />
      <circle cx="12" cy="12" r="2" />
    </>
  ),
  'game.fun-facts': (
    <>
      {/* lucide/lightbulb */}
      {/* the bulb belongs to the fact deck; action.hint takes the question mark. */}
      <path d="M15 14c.2-1 .7-1.7 1.5-2.5 1-.9 1.5-2.2 1.5-3.5A6 6 0 0 0 6 8c0 1 .2 2.2 1.5 3.5.7.7 1.3 1.5 1.5 2.5" />
      <path d="M9 18h6" />
      <path d="M10 22h4" />
    </>
  ),
  'game.coin-pusher': (
    <>
      {/* lucide/coins */}
      <path d="M13.744 17.736a6 6 0 1 1-7.48-7.48" />
      <path d="M15 6h1v4" />
      <path d="m6.134 14.768.866-.5 2 3.464" />
      <circle cx="16" cy="8" r="6" />
    </>
  ),
  'game.high-striker': (
    <>
      {/* lucide/hammer */}
      {/* the long-handled hammer. whack-a-mole shared 🔨 and keeps the bespoke mallet. */}
      <path d="m15 12-9.373 9.373a1 1 0 0 1-3.001-3L12 9" />
      <path d="m18 15 4-4" />
      <path d="m21.5 11.5-1.914-1.914A2 2 0 0 1 19 8.172v-.344a2 2 0 0 0-.586-1.414l-1.657-1.657A6 6 0 0 0 12.516 3H9l1.243 1.243A6 6 0 0 1 12 8.485V10l2 2h1.172a2 2 0 0 1 1.414.586L18.5 14.5" />
    </>
  ),
  'game.trivia': (
    <>
      {/* lucide/brain */}
      <path d="M12 18V5" />
      <path d="M15 13a4.17 4.17 0 0 1-3-4 4.17 4.17 0 0 1-3 4" />
      <path d="M17.598 6.5A3 3 0 1 0 12 5a3 3 0 1 0-5.598 1.5" />
      <path d="M17.997 5.125a4 4 0 0 1 2.526 5.77" />
      <path d="M18 18a4 4 0 0 0 2-7.464" />
      <path d="M19.967 17.483A4 4 0 1 1 12 18a4 4 0 1 1-7.967-.517" />
      <path d="M6 18a4 4 0 0 1-2-7.464" />
      <path d="M6.003 5.125a4 4 0 0 0-2.526 5.77" />
    </>
  ),
  'score.birdie': (
    <>
      {/* lucide/bird */}
      <path d="M16 7h.01" />
      <path d="M3.4 18H12a8 8 0 0 0 8-8V7a4 4 0 0 0-7.28-2.3L2 20" />
      <path d="m20 7 2 .5-2 .5" />
      <path d="M10 18v3" />
      <path d="M14 17.75V21" />
      <path d="M7 18a6 6 0 0 0 3.84-10.61" />
    </>
  ),
  'score.bogey': (
    <>
      {/* lucide/annoyed */}
      {/* a wince. state.lose shared the idea and takes the frown. */}
      <path d="M14 10h2" />
      <path d="M8 10h2" />
      <path d="M8 16h8" />
      <circle cx="12" cy="12" r="10" />
    </>
  ),
  'score.endless': (
    <>
      {/* lucide/infinity */}
      <path d="M6 16c5 0 7-8 12-8a4 4 0 0 1 0 8c-5 0-7-8-12-8a4 4 0 1 0 0 8" />
    </>
  ),
  'score.water-hazard': (
    <>
      {/* lucide/droplets */}
      {/* water as a hazard. game.water-gun-race shared 💦 and keeps the aimed jet. */}
      <path d="M7 16.3c2.2 0 4-1.83 4-4.05 0-1.16-.57-2.26-1.71-3.19S7.29 6.75 7 5.3c-.29 1.45-1.14 2.84-2.29 3.76S3 11.1 3 12.25c0 2.22 1.8 4.05 4 4.05z" />
      <path d="M12.56 6.6A10.97 10.97 0 0 0 14 3.02c.5 2.5 2 4.9 4 6.5s3 3.5 3 5.5a6.98 6.98 0 0 1-11.91 4.97" />
    </>
  ),
  'award.trophy': (
    <>
      {/* lucide/trophy */}
      {/* the object won. action.leaderboard shared 🏆 and takes the ranked list. */}
      <path d="M10 14.66V17a1 1 0 0 1-1 1 2 2 0 0 0-2 2v2" />
      <path d="M14 14.66V17a1 1 0 0 0 1 1 2 2 0 0 1 2 2v2" />
      <path d="M17.916 10H19.5A2.5 2.5 0 0 0 22 7.5V5a1 1 0 0 0-1-1h-3" />
      <path d="M4 22h16" />
      <path d="M6 9a6 6 0 0 0 12 0V3a1 1 0 0 0-1-1H7a1 1 0 0 0-1 1z" />
      <path d="M6.084 10H4.5A2.5 2.5 0 0 1 2 7.5V5a1 1 0 0 1 1-1h3" />
    </>
  ),
  'award.medal': (
    <>
      {/* lucide/medal */}
      <path d="M7.21 15 2.66 7.14a2 2 0 0 1 .13-2.2L4.4 2.8A2 2 0 0 1 6 2h12a2 2 0 0 1 1.6.8l1.6 2.14a2 2 0 0 1 .14 2.2L16.79 15" />
      <path d="M11 12 5.12 2.2" />
      <path d="m13 12 5.88-9.8" />
      <path d="M8 7h8" />
      <circle cx="12" cy="17" r="5" />
      <path d="M12 18v-2h-.5" />
    </>
  ),
  'award.ticket': (
    <>
      {/* lucide/ticket */}
      <path d="M2 9a3 3 0 0 1 0 6v2a2 2 0 0 0 2 2h16a2 2 0 0 0 2-2v-2a3 3 0 0 1 0-6V7a2 2 0 0 0-2-2H4a2 2 0 0 0-2 2Z" />
      <path d="M13 5v2" />
      <path d="M13 17v2" />
      <path d="M13 11v2" />
    </>
  ),
  'order.received': (
    <>
      {/* lucide/receipt */}
      <path d="M12 17V7" />
      <path d="M16 8h-6a2 2 0 0 0 0 4h4a2 2 0 0 1 0 4H8" />
      <path d="M4 3a1 1 0 0 1 1-1 1.3 1.3 0 0 1 .7.2l.933.6a1.3 1.3 0 0 0 1.4 0l.934-.6a1.3 1.3 0 0 1 1.4 0l.933.6a1.3 1.3 0 0 0 1.4 0l.933-.6a1.3 1.3 0 0 1 1.4 0l.934.6a1.3 1.3 0 0 0 1.4 0l.933-.6A1.3 1.3 0 0 1 19 2a1 1 0 0 1 1 1v18a1 1 0 0 1-1 1 1.3 1.3 0 0 1-.7-.2l-.933-.6a1.3 1.3 0 0 0-1.4 0l-.934.6a1.3 1.3 0 0 1-1.4 0l-.933-.6a1.3 1.3 0 0 0-1.4 0l-.933.6a1.3 1.3 0 0 1-1.4 0l-.934-.6a1.3 1.3 0 0 0-1.4 0l-.933.6a1.3 1.3 0 0 1-.7.2 1 1 0 0 1-1-1z" />
    </>
  ),
  'order.sent-to-kitchen': (
    <>
      {/* lucide/send-horizontal */}
      <path d="M3.714 3.048a.498.498 0 0 0-.683.627l2.843 7.627a2 2 0 0 1 0 1.396l-2.842 7.627a.498.498 0 0 0 .682.627l18-8.5a.5.5 0 0 0 0-.904z" />
      <path d="M6 12h16" />
    </>
  ),
  'order.being-prepared': (
    <>
      {/* lucide/cooking-pot */}
      <path d="M2 12h20" />
      <path d="M20 12v8a2 2 0 0 1-2 2H6a2 2 0 0 1-2-2v-8" />
      <path d="m4 8 16-4" />
      <path d="m8.86 6.78-.45-1.81a2 2 0 0 1 1.45-2.43l1.94-.48a2 2 0 0 1 2.43 1.46l.45 1.8" />
    </>
  ),
  'order.ready': (
    <>
      {/* lucide/bell */}
      {/* the still bell. order.notify shared 🔔 and takes the ringing one. */}
      <path d="M10.268 21a2 2 0 0 0 3.464 0" />
      <path d="M3.262 15.326A1 1 0 0 0 4 17h16a1 1 0 0 0 .74-1.673C19.41 13.956 18 12.499 18 8A6 6 0 0 0 6 8c0 4.499-1.411 5.956-2.738 7.326" />
    </>
  ),
  'order.notify': (
    <>
      {/* lucide/bell-ring */}
      {/* the bell mid-ring — an alert being armed, not food being ready. */}
      <path d="M10.268 21a2 2 0 0 0 3.464 0" />
      <path d="M22 8c0-2.3-.8-4.3-2-6" />
      <path d="M3.262 15.326A1 1 0 0 0 4 17h16a1 1 0 0 0 .74-1.673C19.41 13.956 18 12.499 18 8A6 6 0 0 0 6 8c0 4.499-1.411 5.956-2.738 7.326" />
      <path d="M4 2C2.8 3.7 2 5.7 2 8" />
    </>
  ),
  'order.picked-up': (
    <>
      {/* lucide/hand-platter */}
      {/* a plate handed over. state.celebrate shared 🎉 and keeps the popper. */}
      <path d="M12 3V2" />
      <path d="m15.4 17.4 3.2-2.8a2 2 0 1 1 2.8 2.9l-3.6 3.3c-.7.8-1.7 1.2-2.8 1.2h-4c-1.1 0-2.1-.4-2.8-1.2l-1.302-1.464A1 1 0 0 0 6.151 19H5" />
      <path d="M2 14h12a2 2 0 0 1 0 4h-2" />
      <path d="M4 10h16" />
      <path d="M5 10a7 7 0 0 1 14 0" />
      <path d="M5 14v6a1 1 0 0 1-1 1H2" />
    </>
  ),
  'order.cart': (
    <>
      {/* lucide/shopping-basket */}
      <path d="m15 11-1 9" />
      <path d="m19 11-4-7" />
      <path d="M2 11h20" />
      <path d="m3.5 11 1.6 7.4a2 2 0 0 0 2 1.6h9.8a2 2 0 0 0 2-1.6l1.7-7.4" />
      <path d="M4.5 15.5h15" />
      <path d="m5 11 4-7" />
      <path d="m9 11 1 9" />
    </>
  ),
  'action.take-photo': (
    <>
      {/* lucide/aperture */}
      {/* the shutter itself, so the booth’s action differs from nav.photos. */}
      <circle cx="12" cy="12" r="10" />
      <path d="m14.31 8 5.74 9.94" />
      <path d="M9.69 8h11.48" />
      <path d="m7.38 12 5.74-9.94" />
      <path d="M9.69 16 3.95 6.06" />
      <path d="M14.31 16H2.83" />
      <path d="m16.62 12-5.74 9.94" />
    </>
  ),
  'action.share': (
    <>
      {/* lucide/share-2 */}
      <circle cx="18" cy="5" r="3" />
      <circle cx="6" cy="12" r="3" />
      <circle cx="18" cy="19" r="3" />
      <line x1="8.59" x2="15.42" y1="13.51" y2="17.49" />
      <line x1="15.41" x2="8.59" y1="6.51" y2="10.49" />
    </>
  ),
  'action.delete': (
    <>
      {/* lucide/trash-2 */}
      <path d="M10 11v6" />
      <path d="M14 11v6" />
      <path d="M19 6v14a2 2 0 0 1-2 2H7a2 2 0 0 1-2-2V6" />
      <path d="M3 6h18" />
      <path d="M8 6V4a2 2 0 0 1 2-2h4a2 2 0 0 1 2 2v2" />
    </>
  ),
  'action.edit': (
    <>
      {/* lucide/pencil */}
      <path d="M21.174 6.812a1 1 0 0 0-3.986-3.987L3.842 16.174a2 2 0 0 0-.5.83l-1.321 4.352a.5.5 0 0 0 .623.622l4.353-1.32a2 2 0 0 0 .83-.497z" />
      <path d="m15 5 4 4" />
    </>
  ),
  'action.hint': (
    <>
      {/* lucide/circle-help */}
      {/* asking for help. game.fun-facts shared 💡 and keeps the bulb. */}
      <circle cx="12" cy="12" r="10" />
      <path d="M9.09 9a3 3 0 0 1 5.83 1c0 2-3 3-3 3" />
      <path d="M12 17h.01" />
    </>
  ),
  'action.refresh': (
    <>
      {/* lucide/refresh-cw */}
      <path d="M3 12a9 9 0 0 1 9-9 9.75 9.75 0 0 1 6.74 2.74L21 8" />
      <path d="M21 3v5h-5" />
      <path d="M21 12a9 9 0 0 1-9 9 9.75 9.75 0 0 1-6.74-2.74L3 16" />
      <path d="M8 16H3v5" />
    </>
  ),
  'action.feedback': (
    <>
      {/* lucide/message-circle */}
      <path d="M2.992 16.342a2 2 0 0 1 .094 1.167l-1.065 3.29a1 1 0 0 0 1.236 1.168l3.413-.998a2 2 0 0 1 1.099.092 10 10 0 1 0-4.777-4.719" />
    </>
  ),
  'action.play-together': (
    <>
      {/* lucide/smartphone */}
      <rect width="14" height="20" x="5" y="2" rx="2" ry="2" />
      <path d="M12 18h.01" />
    </>
  ),
  'action.rules': (
    <>
      {/* lucide/book-open */}
      <path d="M12 5v16" />
      <path d="M20.001 19A2 2 0 0022 17V5a2 2 0 00-1.999-2L16 3.002A5 5 0 0012 5a5 5 0 00-4-2H4a2 2 0 00-2 2v12a2 2 0 001.999 2H8a5 5 0 014 2 5 5 0 014-2z" />
    </>
  ),
  'action.scorecard': (
    <>
      {/* lucide/clipboard-list */}
      <rect width="8" height="4" x="8" y="2" rx="1" ry="1" />
      <path d="M16 4h2a2 2 0 0 1 2 2v14a2 2 0 0 1-2 2H6a2 2 0 0 1-2-2V6a2 2 0 0 1 2-2h2" />
      <path d="M12 11h4" />
      <path d="M12 16h4" />
      <path d="M8 11h.01" />
      <path d="M8 16h.01" />
    </>
  ),
  'action.leaderboard': (
    <>
      {/* lucide/list-ordered */}
      {/* a ranked list — where standings live, not the cup itself. */}
      <path d="M11 5h10" />
      <path d="M11 12h10" />
      <path d="M11 19h10" />
      <path d="M4 4h1v5" />
      <path d="M4 9h2" />
      <path d="M6.5 20H3.4c0-1 2.6-1.925 2.6-3.5a1.5 1.5 0 0 0-2.6-1.02" />
    </>
  ),
  'control.skin': (
    <>
      {/* lucide/palette */}
      <path d="M12 22a1 1 0 0 1 0-20 10 9 0 0 1 10 9 5 5 0 0 1-5 5h-2.25a1.75 1.75 0 0 0-1.4 2.8l.3.4a1.75 1.75 0 0 1-1.4 2.8z" />
      <circle cx="13.5" cy="6.5" r=".5" fill="currentColor" />
      <circle cx="17.5" cy="10.5" r=".5" fill="currentColor" />
      <circle cx="6.5" cy="12.5" r=".5" fill="currentColor" />
      <circle cx="8.5" cy="7.5" r=".5" fill="currentColor" />
    </>
  ),
  'control.theme-light': (
    <>
      {/* lucide/sun */}
      <circle cx="12" cy="12" r="4" />
      <path d="M12 2v2" />
      <path d="M12 20v2" />
      <path d="m4.93 4.93 1.41 1.41" />
      <path d="m17.66 17.66 1.41 1.41" />
      <path d="M2 12h2" />
      <path d="M20 12h2" />
      <path d="m6.34 17.66-1.41 1.41" />
      <path d="m19.07 4.93-1.41 1.41" />
    </>
  ),
  'control.theme-dark': (
    <>
      {/* lucide/moon */}
      <path d="M20.985 12.486a9 9 0 1 1-9.473-9.472c.405-.022.617.46.402.803a6 6 0 0 0 8.268 8.268c.344-.215.825-.004.803.401" />
    </>
  ),
  'control.sound-on': (
    <>
      {/* lucide/volume-2 */}
      <path d="M11 4.702a.705.705 0 0 0-1.203-.498L6.413 7.587A1.4 1.4 0 0 1 5.416 8H3a1 1 0 0 0-1 1v6a1 1 0 0 0 1 1h2.416a1.4 1.4 0 0 1 .997.413l3.383 3.384A.705.705 0 0 0 11 19.298z" />
      <path d="M16 9a5 5 0 0 1 0 6" />
      <path d="M19.364 18.364a9 9 0 0 0 0-12.728" />
    </>
  ),
  'control.sound-off': (
    <>
      {/* lucide/volume-x */}
      <path d="M11 4.702a.705.705 0 0 0-1.203-.498L6.413 7.587A1.4 1.4 0 0 1 5.416 8H3a1 1 0 0 0-1 1v6a1 1 0 0 0 1 1h2.416a1.4 1.4 0 0 1 .997.413l3.383 3.384A.705.705 0 0 0 11 19.298z" />
      <line x1="22" x2="16" y1="9" y2="15" />
      <line x1="16" x2="22" y1="9" y2="15" />
    </>
  ),
  'state.done': (
    <>
      {/* lucide/circle-check */}
      <circle cx="12" cy="12" r="10" />
      <path d="m9 12 2 2 4-4" />
    </>
  ),
  'state.locked': (
    <>
      {/* lucide/lock */}
      <rect width="18" height="11" x="3" y="11" rx="2" ry="2" />
      <path d="M7 11V7a5 5 0 0 1 10 0v4" />
    </>
  ),
  'state.account': (
    <>
      {/* lucide/circle-user */}
      {/* the enclosed bust — signed in. nav.me keeps the bare one. */}
      <circle cx="12" cy="12" r="10" />
      <circle cx="12" cy="10" r="3" />
      <path d="M7 20.662V19a2 2 0 0 1 2-2h6a2 2 0 0 1 2 2v1.662" />
    </>
  ),
  'state.guest': (
    <>
      {/* lucide/sparkles */}
      <path d="M11.017 2.814a1 1 0 0 1 1.966 0l1.051 5.558a2 2 0 0 0 1.594 1.594l5.558 1.051a1 1 0 0 1 0 1.966l-5.558 1.051a2 2 0 0 0-1.594 1.594l-1.051 5.558a1 1 0 0 1-1.966 0l-1.051-5.558a2 2 0 0 0-1.594-1.594l-5.558-1.051a1 1 0 0 1 0-1.966l5.558-1.051a2 2 0 0 0 1.594-1.594z" />
      <path d="M20 2v4" />
      <path d="M22 4h-4" />
      <circle cx="4" cy="20" r="2" />
    </>
  ),
  'state.teams': (
    <>
      {/* lucide/users */}
      <path d="M16 21v-2a4 4 0 0 0-4-4H6a4 4 0 0 0-4 4v2" />
      <path d="M16 3.128a4 4 0 0 1 0 7.744" />
      <path d="M22 21v-2a4 4 0 0 0-3-3.87" />
      <circle cx="9" cy="7" r="4" />
    </>
  ),
  'state.located': (
    <>
      {/* lucide/map-pin-check */}
      {/* a confirmed pin — you are here. nav.locations keeps the plain pin. */}
      <path d="M19.43 12.935c.357-.967.57-1.955.57-2.935a8 8 0 0 0-16 0c0 4.993 5.539 10.193 7.399 11.799a1 1 0 0 0 1.202 0 32.197 32.197 0 0 0 .813-.728" />
      <circle cx="12" cy="10" r="3" />
      <path d="m16 18 2 2 4-4" />
    </>
  ),
  'state.no-venue': (
    <>
      {/* lucide/compass */}
      <circle cx="12" cy="12" r="10" />
      <path d="m16.24 7.76-1.804 5.411a2 2 0 0 1-1.265 1.265L7.76 16.24l1.804-5.411a2 2 0 0 1 1.265-1.265z" />
    </>
  ),
  'state.announcement': (
    <>
      {/* lucide/megaphone */}
      <path d="M11 6a13 13 0 0 0 8.4-2.8A1 1 0 0 1 21 4v12a1 1 0 0 1-1.6.8A13 13 0 0 0 11 14H5a2 2 0 0 1-2-2V8a2 2 0 0 1 2-2z" />
      <path d="M6 14a12 12 0 0 0 2.4 7.2 2 2 0 0 0 3.2-2.4A8 8 0 0 1 10 14" />
      <path d="M8 6v8" />
    </>
  ),
  'state.cpu': (
    <>
      {/* lucide/bot */}
      <path d="M12 8V4H8" />
      <rect width="16" height="12" x="4" y="8" rx="2" />
      <path d="M2 14h2" />
      <path d="M20 14h2" />
      <path d="M15 13v2" />
      <path d="M9 13v2" />
    </>
  ),
  'state.timer': (
    <>
      {/* lucide/timer */}
      <line x1="10" x2="14" y1="2" y2="2" />
      <line x1="12" x2="15" y1="14" y2="11" />
      <circle cx="12" cy="14" r="8" />
    </>
  ),
  'state.celebrate': (
    <>
      {/* lucide/party-popper */}
      <path d="M5.8 11.3 2 22l10.7-3.79" />
      <path d="M4 3h.01" />
      <path d="M22 8h.01" />
      <path d="M15 2h.01" />
      <path d="M22 20h.01" />
      <path d="m22 2-2.24.75a2.9 2.9 0 0 0-1.96 3.12c.1.86-.57 1.63-1.45 1.63h-.38c-.86 0-1.6.6-1.76 1.44L14 10" />
      <path d="m22 13-.82-.33c-.86-.34-1.82.2-1.98 1.11c-.11.7-.72 1.22-1.43 1.22H17" />
      <path d="m11 2 .33.82c.34.86-.2 1.82-1.11 1.98C9.52 4.9 9 5.52 9 6.23V7" />
      <path d="M11 13c1.93 1.93 2.83 4.17 2 5-.83.83-3.07-.07-5-2-1.93-1.93-2.83-4.17-2-5 .83-.83 3.07.07 5 2Z" />
    </>
  ),
  'state.win': (
    <>
      {/* lucide/balloon */}
      <path d="M12 16v1a2 2 0 0 0 2 2h1a2 2 0 0 1 2 2v1" />
      <path d="M12 6a2 2 0 0 1 2 2" />
      <path d="M18 8c0 4-3.5 8-6 8s-6-4-6-8a6 6 0 0 1 12 0" />
    </>
  ),
  'state.lose': (
    <>
      {/* lucide/frown */}
      {/* a flat frown. score.bogey shared the idea and takes the wince. */}
      <path d="M15 10V9" />
      <path d="M9 10V9" />
      <path d="M9 16a5 5 0 016 0" />
      <circle cx="12" cy="12" r="10" />
    </>
  ),
  'brand.mark': (
    <>
      {/* lucide/ferris-wheel */}
      <circle cx="12" cy="12" r="2" />
      <path d="M12 2v4" />
      <path d="m6.8 15-3.5 2" />
      <path d="m20.7 7-3.5 2" />
      <path d="M6.8 9 3.3 7" />
      <path d="m20.7 17-3.5-2" />
      <path d="m9 22 3-8 3 8" />
      <path d="M8 22h8" />
      <path d="M18 18.7a9 9 0 1 0-12 0" />
    </>
  ),
  'course.blue': (
    <>
      {/* lucide/circle */}
      {/* a bare ring; the course accent colour carries the identity. */}
      <circle cx="12" cy="12" r="10" />
    </>
  ),
  'course.green': (
    <>
      {/* lucide/circle */}
      <circle cx="12" cy="12" r="10" />
    </>
  ),
  'course.red': (
    <>
      {/* lucide/circle */}
      <circle cx="12" cy="12" r="10" />
    </>
  ),
  'course.california': (
    <>
      {/* lucide/tree-palm */}
      {/* a palm. course.jungle shared 🌴 and takes the broadleaf grove. */}
      <path d="M13 8c0-2.76-2.46-5-5.5-5S2 5.24 2 8h2l1-1 1 1h4" />
      <path d="M13 7.14A5.82 5.82 0 0 1 16.5 6c3.04 0 5.5 2.24 5.5 5h-3l-1-1-1 1h-3" />
      <path d="M5.89 9.71c-2.15 2.15-2.3 5.47-.35 7.43l4.24-4.25.7-.7.71-.71 2.12-2.12c-1.95-1.96-5.27-1.8-7.42.35" />
      <path d="M11 15.5c.5 2.5-.17 4.5-1 6.5h4c2-5.5-.5-12-1-14" />
    </>
  ),
  'course.jungle': (
    <>
      {/* lucide/trees */}
      {/* a grove, so the two 🌴 courses stop being the same picture. */}
      <path d="M10 10v.2A3 3 0 0 1 8.9 16H5a3 3 0 0 1-1-5.8V10a3 3 0 0 1 6 0Z" />
      <path d="M7 16v6" />
      <path d="M13 19v3" />
      <path d="M12 19h8.3a1 1 0 0 0 .7-1.7L18 14h.3a1 1 0 0 0 .7-1.7L16 9h.2a1 1 0 0 0 .8-1.7L13 3l-1.4 1.5" />
    </>
  ),
  'course.pirate': (
    <>
      {/* lucide/skull */}
      <path d="m12.5 17-.5-1-.5 1h1z" />
      <path d="M15 22a1 1 0 0 0 1-1v-1a2 2 0 0 0 1.56-3.25 8 8 0 1 0-11.12 0A2 2 0 0 0 8 20v1a1 1 0 0 0 1 1z" />
      <circle cx="15" cy="12" r="1" />
      <circle cx="9" cy="12" r="1" />
    </>
  ),
  'course.space': (
    <>
      {/* lucide/rocket */}
      <path d="M12 15v5s3.03-.55 4-2c1.08-1.62 0-5 0-5" />
      <path d="M4.5 16.5c-1.5 1.26-2 5-2 5s3.74-.5 5-2c.71-.84.7-2.13-.09-2.91a2.18 2.18 0 0 0-2.91-.09" />
      <path d="M9 12a22 22 0 0 1 2-3.95A12.88 12.88 0 0 1 22 2c0 2.72-.78 7.5-6 11a22.4 22.4 0 0 1-4 2z" />
      <path d="M9 12H4s.55-3.03 2-4c1.62-1.08 5 .05 5 .05" />
    </>
  ),
  'course.haunted': (
    <>
      {/* lucide/ghost */}
      <path d="M9 10h.01" />
      <path d="M15 10h.01" />
      <path d="M12 2a8 8 0 0 0-8 8v12l3-3 2.5 2.5L12 19l2.5 2.5L17 19l3 3V10a8 8 0 0 0-8-8z" />
    </>
  ),
} satisfies Partial<Record<IconName, ReactNode>>;

/** Which upstream icon each drawing came from — provenance for the licence
 *  note above, and what a redraw or an upstream bump has to be checked against. */
export const VENDORED_SOURCE: Partial<Record<IconName, string>> = {
  'nav.home': 'lucide/house',
  'nav.golf': 'lucide/flag-triangle-right',
  'nav.arcade': 'lucide/gamepad-2',
  'nav.food': 'lucide/utensils',
  'nav.photos': 'lucide/camera',
  'nav.hunt': 'lucide/search',
  'nav.me': 'lucide/user',
  'nav.locations': 'lucide/map-pin',
  'nav.install': 'lucide/download',
  'nav.rewards': 'lucide/ticket',
  'game.axe-throwing': 'lucide/axe',
  'game.darts': 'lucide/target',
  'game.fun-facts': 'lucide/lightbulb',
  'game.coin-pusher': 'lucide/coins',
  'game.high-striker': 'lucide/hammer',
  'game.trivia': 'lucide/brain',
  'score.birdie': 'lucide/bird',
  'score.bogey': 'lucide/annoyed',
  'score.endless': 'lucide/infinity',
  'score.water-hazard': 'lucide/droplets',
  'award.trophy': 'lucide/trophy',
  'award.medal': 'lucide/medal',
  'award.ticket': 'lucide/ticket',
  'order.received': 'lucide/receipt',
  'order.sent-to-kitchen': 'lucide/send-horizontal',
  'order.being-prepared': 'lucide/cooking-pot',
  'order.ready': 'lucide/bell',
  'order.notify': 'lucide/bell-ring',
  'order.picked-up': 'lucide/hand-platter',
  'order.cart': 'lucide/shopping-basket',
  'action.take-photo': 'lucide/aperture',
  'action.share': 'lucide/share-2',
  'action.delete': 'lucide/trash-2',
  'action.edit': 'lucide/pencil',
  'action.hint': 'lucide/circle-help',
  'action.refresh': 'lucide/refresh-cw',
  'action.feedback': 'lucide/message-circle',
  'action.play-together': 'lucide/smartphone',
  'action.rules': 'lucide/book-open',
  'action.scorecard': 'lucide/clipboard-list',
  'action.leaderboard': 'lucide/list-ordered',
  'control.skin': 'lucide/palette',
  'control.theme-light': 'lucide/sun',
  'control.theme-dark': 'lucide/moon',
  'control.sound-on': 'lucide/volume-2',
  'control.sound-off': 'lucide/volume-x',
  'state.done': 'lucide/circle-check',
  'state.locked': 'lucide/lock',
  'state.account': 'lucide/circle-user',
  'state.guest': 'lucide/sparkles',
  'state.teams': 'lucide/users',
  'state.located': 'lucide/map-pin-check',
  'state.no-venue': 'lucide/compass',
  'state.announcement': 'lucide/megaphone',
  'state.cpu': 'lucide/bot',
  'state.timer': 'lucide/timer',
  'state.celebrate': 'lucide/party-popper',
  'state.win': 'lucide/balloon',
  'state.lose': 'lucide/frown',
  'brand.mark': 'lucide/ferris-wheel',
  'course.blue': 'lucide/circle',
  'course.green': 'lucide/circle',
  'course.red': 'lucide/circle',
  'course.california': 'lucide/tree-palm',
  'course.jungle': 'lucide/trees',
  'course.pirate': 'lucide/skull',
  'course.space': 'lucide/rocket',
  'course.haunted': 'lucide/ghost',
  'game.bowling': 'phosphor-bold/bowling-ball',
  'game.arcade-putt': 'phosphor-bold/golf',
  'game.pop-a-shot': 'phosphor-bold/basketball',
  'game.batting-cages': 'phosphor-bold/baseball',
  'game.air-hockey': 'phosphor-bold/hockey',
  'game.go-karts': 'phosphor-bold/steering-wheel',
  'state.finish': 'phosphor-bold/flag-checkered',
};

/**
 * Phosphor, bold weight. FILLED paths on a 256 grid, so <Icon> renders these
 * with fill=currentColor and no stroke — a different coordinate system and a
 * different rendering mode from everything above, which is why they are a
 * separate export rather than more entries in VENDORED_ART.
 *
 * The trade is in scripts/vendor-icons.mjs: these seven cannot take a
 * stroke-width change, which no skin does today.
 */
export const FILLED_ART = {
  'game.bowling': (
    <>
      {/* phosphor/bowling-ball (bold) */}
      {/* the ball with finger holes. game.skee-ball keeps the bespoke alley, so the pair is now BALL vs ALLEY. */}
      <path d="M128,20A108,108,0,1,0,236,128,108.12,108.12,0,0,0,128,20Zm0,192a84,84,0,1,1,84-84A84.09,84.09,0,0,1,128,212Zm16-84a16,16,0,1,1-16-16A16,16,0,0,1,144,128Zm16-16a16,16,0,1,1,16-16A16,16,0,0,1,160,112Zm32,24a16,16,0,1,1-16-16A16,16,0,0,1,192,136Z"/>
    </>
  ),
  'game.arcade-putt': (
    <>
      {/* phosphor/golf (bold) */}
      {/* a ball on a tee. nav.golf keeps the pennant, so the mini-game and the real course stay apart. */}
      <path d="M180,100a16,16,0,1,1-16-16A16,16,0,0,1,180,100Zm-48,16a16,16,0,1,0,16,16A16,16,0,0,0,132,116Zm88-20A92,92,0,1,1,128,4,92.1,92.1,0,0,1,220,96Zm-24,0a68,68,0,1,0-68,68A68.07,68.07,0,0,0,196,96ZM164,197.86a108.61,108.61,0,0,1-72,0,12,12,0,0,0-8,22.63,131.83,131.83,0,0,0,32,7V244a12,12,0,0,0,24,0V227.46a131.83,131.83,0,0,0,32-7,12,12,0,0,0-8-22.63Z"/>
    </>
  ),
  'game.pop-a-shot': (
    <>
      {/* phosphor/basketball (bold) */}
      {/* the ball rather than the hoop — it survives 24px, which my backboard-and-net did not. */}
      <path d="M128,20A108,108,0,1,0,236,128,108.12,108.12,0,0,0,128,20ZM60,177.28A83.59,83.59,0,0,1,44.87,140H75.14A83.1,83.1,0,0,1,60,177.28ZM44.87,116A83.59,83.59,0,0,1,60,78.72,83.1,83.1,0,0,1,75.14,116ZM116,211.13a83.63,83.63,0,0,1-39-16.46A106.94,106.94,0,0,0,99.34,140H116ZM116,116H99.34A106.94,106.94,0,0,0,77,61.33a83.63,83.63,0,0,1,39-16.46Zm80-37.28A83.59,83.59,0,0,1,211.13,116H180.86A83.1,83.1,0,0,1,196,78.72ZM140,211.13V140h16.66A106.94,106.94,0,0,0,179,194.67,83.63,83.63,0,0,1,140,211.13ZM156.66,116H140V44.87a83.63,83.63,0,0,1,39,16.46A106.94,106.94,0,0,0,156.66,116ZM196,177.28A83.1,83.1,0,0,1,180.86,140h30.27A83.59,83.59,0,0,1,196,177.28Z"/>
    </>
  ),
  'game.batting-cages': (
    <>
      {/* phosphor/baseball (bold) */}
      <path d="M128,20A108,108,0,1,0,236,128,108.12,108.12,0,0,0,128,20ZM77,194.66A108.9,108.9,0,0,0,85.54,182a12,12,0,1,0-20.77-12A83.28,83.28,0,0,1,60,177.27a83.73,83.73,0,0,1,0-98.54A83.28,83.28,0,0,1,64.77,86,12,12,0,1,0,85.54,74,108.9,108.9,0,0,0,77,61.34a83.76,83.76,0,0,1,102.06,0A108.9,108.9,0,0,0,170.46,74a12,12,0,1,0,20.77,12A83.28,83.28,0,0,1,196,78.73a83.73,83.73,0,0,1,0,98.54,83.28,83.28,0,0,1-4.74-7.28,12,12,0,1,0-20.77,12A108.9,108.9,0,0,0,179,194.66a83.76,83.76,0,0,1-102.06,0Zm22.2-80.14A110,110,0,0,1,100,128a110,110,0,0,1-.83,13.48A12,12,0,0,1,87.27,152a12.83,12.83,0,0,1-1.5-.09,12,12,0,0,1-10.42-13.39A85.75,85.75,0,0,0,76,128a85.75,85.75,0,0,0-.65-10.52,12,12,0,1,1,23.82-3Zm71.06,37.39a12.83,12.83,0,0,1-1.5.09,12,12,0,0,1-11.9-10.52,109.88,109.88,0,0,1,0-27,12,12,0,1,1,23.82,3,85.46,85.46,0,0,0,0,21A12,12,0,0,1,170.23,151.91Z"/>
    </>
  ),
  'game.air-hockey': (
    <>
      {/* phosphor/hockey (bold) */}
      {/* crossed sticks. Not strictly an air-hockey striker, but it matches the 🏒 the app already chose and reads at size. */}
      <path d="M224,148H132.75L41.14,40.23A12,12,0,0,0,22.86,55.77l95.16,112,.06.07L156.46,213A20,20,0,0,0,171.7,220H224a20,20,0,0,0,20-20V168A20,20,0,0,0,224,148Zm-70.85,24H180v24h-6.45ZM220,196H204V172h16Zm-66.34-83.77,61.2-72a12,12,0,0,1,18.28,15.54l-61.2,72a12,12,0,1,1-18.28-15.54Zm-44.14,70.45a12,12,0,0,0-16.91,1.37L82.45,196H76V171.93A12,12,0,0,0,74.7,148H32a20,20,0,0,0-20,20v32a20,20,0,0,0,20,20H84.3A20,20,0,0,0,99.54,213l11.35-13.36A12,12,0,0,0,109.52,182.68ZM36,172H52v24H36Z"/>
    </>
  ),
  'game.go-karts': (
    <>
      {/* phosphor/steering-wheel (bold) */}
      {/* a wheel, which frees the chequered flag for state.finish — what 🏁 actually meant. */}
      <path d="M144,144a16,16,0,1,1-16-16A16,16,0,0,1,144,144Zm92-16A108,108,0,1,1,128,20,108.12,108.12,0,0,1,236,128Zm-70.45,28h41.63c.79-2.21,1.49-4.47,2.09-6.76a116,116,0,0,0-162.54,0q.9,3.44,2.09,6.76H90.45a20.07,20.07,0,0,1,18.73,13l16.06,42.93c.92,0,1.83.07,2.76.07s1.82,0,2.72-.07l16.1-43A20.09,20.09,0,0,1,165.55,156ZM44.41,119.73a139.85,139.85,0,0,1,167.18,0,84,84,0,0,0-167.18,0Zm53.08,86.51L87.68,180H62.1A84.46,84.46,0,0,0,97.49,206.24ZM193.9,180H168.32l-9.84,26.25A84.35,84.35,0,0,0,193.9,180Z"/>
    </>
  ),
  'state.finish': (
    <>
      {/* phosphor/flag-checkered (bold) */}
      {/* the chequered flag, back now that game.go-karts is a steering wheel and the two no longer collide. */}
      <path d="M229,45a12,12,0,0,0-12.85,1.84c-24.71,21.41-44.53,13.31-74.82-1.68C113.19,31.27,78.17,13.94,40.14,46.88A12,12,0,0,0,36,56V224a12,12,0,0,0,24,0V181.71c22.84-17.13,42.1-9.11,70.68,5,16.23,8,34.74,17.2,54.8,17.2,14.72,0,30.28-4.94,46.38-18.88A12,12,0,0,0,236,176V56A12,12,0,0,0,229,45ZM185.48,83.91A63,63,0,0,0,212,78.08v32.15c-11,8.26-21.2,10.67-32,9.37V83.66C181.81,83.81,183.64,83.91,185.48,83.91ZM156,78.08v34.09c-4.64-2-9.5-4.4-14.68-7A255.21,255.21,0,0,0,116,93.83V59.75c4.64,2,9.5,4.4,14.68,7A252.91,252.91,0,0,0,156,78.08ZM92,52.32V88.24a63.33,63.33,0,0,0-32,5.61V61.68C71,53.42,81.2,51,92,52.32ZM86.52,148A63,63,0,0,0,60,153.86V121.7c11-8.25,21.2-10.66,32-9.36v35.94C90.19,148.13,88.36,148,86.52,148ZM116,153.86V119.77c4.64,2,9.5,4.4,14.68,7A252.91,252.91,0,0,0,156,138.1v34.09c-4.64-2.05-9.5-4.4-14.68-7A250.66,250.66,0,0,0,116,153.86Zm64,25.76V143.68c1.81.14,3.64.24,5.48.24A62.85,62.85,0,0,0,212,138.07v32.19C201,178.52,190.8,180.92,180,179.62Z"/>
    </>
  ),
} satisfies Partial<Record<IconName, ReactNode>>;
