// AUTO-GENERATED by scripts/export-content.mjs — DO NOT EDIT BY HAND.
// The Postgres DB (managed in Master Control) is the source of truth; this file
// is regenerated at build time from GET /api/content and committed so builds are
// reproducible without a live DB. Frontend-only styling (accents, themed rules,
// map art) is merged on top in src/data/courses.ts. See master-control-plan.md §5.

export type GeneratedLocation = {
  id: string;
  name: string;
  slug: string;
  lat: number | null;
  lng: number | null;
  geofenceKm: number | null;
  tz: string | null;
  sortOrder: number;
  orgId: string | null;
};

export type GeneratedCourse = {
  id: string;
  locationId: string | null;
  name: string;
  theme: string;
  holeCount: number;
  pars: number[];
  sortOrder: number;
};

export const GENERATED_LOCATIONS: GeneratedLocation[] = [
  {
    id: "aaaaaaaa-aaaa-4aaa-8aaa-aaaaaaaaaaaa",
    name: "Upland",
    slug: "upland",
    lat: 34.08867,
    lng: -117.67946,
    geofenceKm: 2,
    tz: "America/Los_Angeles",
    sortOrder: 10,
    orgId: "dddddddd-dddd-4ddd-8ddd-dddddddddddd",
  },
  {
    id: "bbbbbbbb-bbbb-4bbb-8bbb-bbbbbbbbbbbb",
    name: "Tukwila",
    slug: "tukwila",
    lat: 47.46562,
    lng: -122.24302,
    geofenceKm: 2,
    tz: "America/Los_Angeles",
    sortOrder: 20,
    orgId: "dddddddd-dddd-4ddd-8ddd-dddddddddddd",
  },
  {
    id: "cccccccc-cccc-4ccc-8ccc-cccccccccccc",
    name: "Wilsonville",
    slug: "wilsonville",
    lat: 45.30969,
    lng: -122.7668,
    geofenceKm: 2,
    tz: "America/Los_Angeles",
    sortOrder: 30,
    orgId: "dddddddd-dddd-4ddd-8ddd-dddddddddddd",
  },
];

export const GENERATED_COURSES: GeneratedCourse[] = [
  {
    id: "a1111111-1111-4111-8111-111111111111",
    locationId: "aaaaaaaa-aaaa-4aaa-8aaa-aaaaaaaaaaaa",
    name: "Blue Course",
    theme: "california",
    holeCount: 18,
    pars: [3,2,3,2,3,4,2,3,2,3,3,2,4,3,2,3,2,3],
    sortOrder: 10,
  },
  {
    id: "a2222222-2222-4222-8222-222222222222",
    locationId: "aaaaaaaa-aaaa-4aaa-8aaa-aaaaaaaaaaaa",
    name: "Green Course",
    theme: "classic",
    holeCount: 18,
    pars: [2,3,2,3,3,2,4,3,2,3,2,3,3,4,2,3,3,2],
    sortOrder: 20,
  },
  {
    id: "a3333333-3333-4333-8333-333333333333",
    locationId: "aaaaaaaa-aaaa-4aaa-8aaa-aaaaaaaaaaaa",
    name: "Dragon's Hollow",
    theme: "dragon",
    holeCount: 18,
    pars: [3,3,4,2,3,3,2,4,3,2,3,4,3,2,3,3,4,2],
    sortOrder: 30,
  },
  {
    id: "a4444444-4444-4444-8444-444444444444",
    locationId: "aaaaaaaa-aaaa-4aaa-8aaa-aaaaaaaaaaaa",
    name: "Western",
    theme: "western",
    holeCount: 18,
    pars: [2,3,3,2,4,3,2,3,3,2,4,3,2,3,3,2,3,4],
    sortOrder: 40,
  },
  {
    id: "b1111111-1111-4111-8111-111111111111",
    locationId: "bbbbbbbb-bbbb-4bbb-8bbb-bbbbbbbbbbbb",
    name: "Blue Course",
    theme: "blue",
    holeCount: 18,
    pars: [3,2,2,3,3,2,3,4,2,3,3,2,3,2,4,3,2,3],
    sortOrder: 10,
  },
  {
    id: "b2222222-2222-4222-8222-222222222222",
    locationId: "bbbbbbbb-bbbb-4bbb-8bbb-bbbbbbbbbbbb",
    name: "Green Course",
    theme: "green",
    holeCount: 18,
    pars: [2,3,3,2,3,3,2,3,4,2,3,2,3,3,2,4,3,2],
    sortOrder: 20,
  },
  {
    id: "b3333333-3333-4333-8333-333333333333",
    locationId: "bbbbbbbb-bbbb-4bbb-8bbb-bbbbbbbbbbbb",
    name: "Red Course",
    theme: "red",
    holeCount: 18,
    pars: [3,3,2,4,2,3,3,2,3,4,2,3,2,3,3,2,4,3],
    sortOrder: 30,
  },
  {
    id: "c1111111-1111-4111-8111-111111111111",
    locationId: "cccccccc-cccc-4ccc-8ccc-cccccccccccc",
    name: "Blue Course",
    theme: "blue",
    holeCount: 18,
    pars: [2,3,2,3,4,2,3,2,3,3,2,4,3,2,3,2,3,3],
    sortOrder: 10,
  },
  {
    id: "c2222222-2222-4222-8222-222222222222",
    locationId: "cccccccc-cccc-4ccc-8ccc-cccccccccccc",
    name: "Green Course",
    theme: "green",
    holeCount: 18,
    pars: [3,2,3,3,2,4,2,3,3,2,3,2,4,3,2,3,2,3],
    sortOrder: 20,
  },
];
