// AUTO-GENERATED by scripts/export-content.mjs — DO NOT EDIT BY HAND.
// The Postgres DB (managed in Master Control) is the source of truth; this file
// is regenerated at build time from GET /api/content and committed so builds are
// reproducible without a live DB. Frontend-only styling (accents, themed rules,
// map art) is merged on top in src/data/courses.ts. See master-control-plan.md §5.

// Weekly business hours (per venue, set in Master Control), evaluated in the
// location's own `tz`. A missing day key = closed; a day may instead be the
// string "closed"; `close` may be "24:00" (midnight) or earlier than `open`
// for an overnight close. See src/lib/venueHours.ts (mirrors
// server/lib/venueHours.js) for the canonical shape doc + open/closed logic.
export type VenueHoursDay = { open: string; close: string } | 'closed';
export type VenueHours = Partial<
  Record<'mon' | 'tue' | 'wed' | 'thu' | 'fri' | 'sat' | 'sun', VenueHoursDay>
>;

export type GeneratedLocation = {
  id: string;
  name: string;
  slug: string;
  lat: number | null;
  lng: number | null;
  geofenceKm: number | null;
  tz: string | null;
  sortOrder: number;
  menuUrl: string | null;
  orderingUrl: string | null;
  hours: VenueHours | null;
  // Course-free scavenger hunt availability, derived server-side (venueMode on
  // + at least one active venue item). Optional: the baked snapshot predates
  // it, and a cached payload from an older server won't carry it.
  venueHunt?: boolean;
  // POS integration add-on (per-venue, set in Master Control). Structurally
  // matches PosConfig in src/lib/pos/types.ts (capabilities decoupled — each
  // names its own vendor); kept inline so this generated file stays
  // import-free.
  pos: {
    ordering: { vendor: string; apiBase: string | null } | null;
    loyalty: {
      vendor: string;
      apiBase: string | null;
      gameRewards: boolean;
      // Venue ticket-economy caps (enforced server-side by the award proxy;
      // carried here only so the config round-trips). Present only when the
      // venue overrides a default.
      gameRewardCaps?: { dailyPerCard: number | null; perGame: Record<string, number> };
    } | null;
  } | null;
  // Resolved a la carte module entitlements (server/lib/modules.js) — the
  // FINAL on/off per module, with vendor wiring and dependencies already
  // folded in, so the client never re-derives them. Optional: the baked
  // snapshot predates it, and a cached payload from an older server won't
  // carry it — absent must read as "derive from pos", the pre-modules
  // behavior (src/lib/modules.ts).
  modules?: Record<string, boolean>;
  orgId: string | null;
};

export type GeneratedCourse = {
  id: string;
  locationId: string | null;
  name: string;
  theme: string;
  holeCount: number;
  pars: number[];
  sortOrder: number;
};

// The tenant org the payload was filtered by (MULTI-VENUE.md §3), or null when
// the server resolved no tenant. `branding` is a partial overlay; the typed
// shape + defaults live in src/lib/branding.ts (kept loose here so this
// generated file stays import-free).
export type GeneratedOrg = {
  id: string;
  slug: string;
  name: string;
  branding: Record<string, string>;
};

export const GENERATED_ORG: GeneratedOrg | null = {
  id: "dddddddd-dddd-4ddd-8ddd-dddddddddddd",
  slug: "bullwinkles",
  name: "Bullwinkle's",
  branding: {},
};

export const GENERATED_LOCATIONS: GeneratedLocation[] = [
  {
    id: "aaaaaaaa-aaaa-4aaa-8aaa-aaaaaaaaaaaa",
    name: "Upland",
    slug: "upland",
    lat: 34.08867,
    lng: -117.67946,
    geofenceKm: 2,
    tz: "America/Los_Angeles",
    sortOrder: 10,
    menuUrl: null,
    orderingUrl: null,
    hours: {
      mon: { open: "12:00", close: "21:00" },
      tue: { open: "12:00", close: "21:00" },
      wed: { open: "12:00", close: "21:00" },
      thu: { open: "12:00", close: "21:00" },
      fri: { open: "12:00", close: "23:00" },
      sat: { open: "11:00", close: "23:00" },
      sun: { open: "11:00", close: "21:00" },
    },
    pos: null,
    orgId: "dddddddd-dddd-4ddd-8ddd-dddddddddddd",
  },
  {
    id: "bbbbbbbb-bbbb-4bbb-8bbb-bbbbbbbbbbbb",
    name: "Tukwila",
    slug: "tukwila",
    lat: 47.46562,
    lng: -122.24302,
    geofenceKm: 2,
    tz: "America/Los_Angeles",
    sortOrder: 20,
    menuUrl: null,
    orderingUrl: null,
    hours: {
      mon: { open: "11:00", close: "21:00" },
      tue: { open: "11:00", close: "21:00" },
      wed: { open: "11:00", close: "21:00" },
      thu: { open: "11:00", close: "21:00" },
      fri: { open: "11:00", close: "23:00" },
      sat: { open: "11:00", close: "23:00" },
      sun: { open: "11:00", close: "22:00" },
    },
    pos: null,
    orgId: "dddddddd-dddd-4ddd-8ddd-dddddddddddd",
  },
  {
    id: "cccccccc-cccc-4ccc-8ccc-cccccccccccc",
    name: "Wilsonville",
    slug: "wilsonville",
    lat: 45.30969,
    lng: -122.7668,
    geofenceKm: 2,
    tz: "America/Los_Angeles",
    sortOrder: 30,
    menuUrl: null,
    orderingUrl: null,
    hours: {
      mon: { open: "11:00", close: "22:00" },
      tue: { open: "11:00", close: "22:00" },
      wed: { open: "11:00", close: "22:00" },
      thu: { open: "11:00", close: "22:00" },
      fri: { open: "11:00", close: "23:00" },
      sat: { open: "11:00", close: "23:00" },
      sun: { open: "11:00", close: "22:00" },
    },
    pos: null,
    orgId: "dddddddd-dddd-4ddd-8ddd-dddddddddddd",
  },
];

export const GENERATED_COURSES: GeneratedCourse[] = [
  {
    id: "a1111111-1111-4111-8111-111111111111",
    locationId: "aaaaaaaa-aaaa-4aaa-8aaa-aaaaaaaaaaaa",
    name: "Blue Course",
    theme: "california",
    holeCount: 18,
    pars: [3,2,3,2,3,4,2,3,2,3,3,2,4,3,2,3,2,3],
    sortOrder: 10,
  },
  {
    id: "a2222222-2222-4222-8222-222222222222",
    locationId: "aaaaaaaa-aaaa-4aaa-8aaa-aaaaaaaaaaaa",
    name: "Green Course",
    theme: "classic",
    holeCount: 18,
    pars: [2,3,2,3,3,2,4,3,2,3,2,3,3,4,2,3,3,2],
    sortOrder: 20,
  },
  {
    id: "a3333333-3333-4333-8333-333333333333",
    locationId: "aaaaaaaa-aaaa-4aaa-8aaa-aaaaaaaaaaaa",
    name: "Dragon's Hollow",
    theme: "dragon",
    holeCount: 18,
    pars: [3,3,4,2,3,3,2,4,3,2,3,4,3,2,3,3,4,2],
    sortOrder: 30,
  },
  {
    id: "a4444444-4444-4444-8444-444444444444",
    locationId: "aaaaaaaa-aaaa-4aaa-8aaa-aaaaaaaaaaaa",
    name: "Western",
    theme: "western",
    holeCount: 18,
    pars: [2,3,3,2,4,3,2,3,3,2,4,3,2,3,3,2,3,4],
    sortOrder: 40,
  },
  {
    id: "b1111111-1111-4111-8111-111111111111",
    locationId: "bbbbbbbb-bbbb-4bbb-8bbb-bbbbbbbbbbbb",
    name: "Blue Course",
    theme: "blue",
    holeCount: 18,
    pars: [3,2,2,3,3,2,3,4,2,3,3,2,3,2,4,3,2,3],
    sortOrder: 10,
  },
  {
    id: "b2222222-2222-4222-8222-222222222222",
    locationId: "bbbbbbbb-bbbb-4bbb-8bbb-bbbbbbbbbbbb",
    name: "Green Course",
    theme: "green",
    holeCount: 18,
    pars: [2,3,3,2,3,3,2,3,4,2,3,2,3,3,2,4,3,2],
    sortOrder: 20,
  },
  {
    id: "b3333333-3333-4333-8333-333333333333",
    locationId: "bbbbbbbb-bbbb-4bbb-8bbb-bbbbbbbbbbbb",
    name: "Red Course",
    theme: "red",
    holeCount: 18,
    pars: [3,3,2,4,2,3,3,2,3,4,2,3,2,3,3,2,4,3],
    sortOrder: 30,
  },
  {
    id: "c1111111-1111-4111-8111-111111111111",
    locationId: "cccccccc-cccc-4ccc-8ccc-cccccccccccc",
    name: "Blue Course",
    theme: "blue",
    holeCount: 18,
    pars: [2,3,2,3,4,2,3,2,3,3,2,4,3,2,3,2,3,3],
    sortOrder: 10,
  },
  {
    id: "c2222222-2222-4222-8222-222222222222",
    locationId: "cccccccc-cccc-4ccc-8ccc-cccccccccccc",
    name: "Green Course",
    theme: "green",
    holeCount: 18,
    pars: [3,2,3,3,2,4,2,3,3,2,3,2,4,3,2,3,2,3],
    sortOrder: 20,
  },
];
